# Site settings
url: ""
name: 'Ali Bar-Bar'
subname: 'Top Shelf Music, Bottom Shelf Drinks'
# Meta
title: "Ali Bar-Bar"
description: "Ali Bar-Bar - Burning Man"

# Links
email: info@alibarbar.org
facebook_page: alibarbarbrc
instagram_username: alibarbar.brc
soundcloud_username:  ali-bar-bar

# Images
avatar: yes
avatar_img_path: "imgs/avatar.jpg"
front_img: yes
front_img_path: "imgs/background.jpg"
favicon_emoji: '🧞‍♂️'

# Build settings
markdown: kramdown
permalink: pretty

exclude: ["LICENSE", README.md]
